name: Retrieve secret Azure Keyvault

on: workflow_dispatch

jobs: 
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURECRED_KEYVAULT }}'

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo secret=$(az keyvault secret show --vault-name WTR-KV-01 --name windowsadmin --query value) >> $GITHUB_ENV

      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.secret }}"